### ISSUE TITLE
Deprecated urlparse module in Python 3

### ISSUE THREAD

**Issue by MelerosPaw** [postrational/har2grinder#3]
In Python 3, urlparse has been renamed to urllib.parse. The import is not working. I imported the new parse module from urllib and used `parse.urlparse` instead. Here's the result: 

`from urllib import parse`

and then in line 111

`parsed_url = parse.urlparse(url)`

Here's the file: [har2grinder.txt](https://github.com/postrational/har2grinder/files/538238/har2grinder.txt)

**Comment by postrational** [comment]
Thanks for the report. I updated the script to work in both Python 2 and Python 3. Try it again.
